-- Baseline schema. Single source of truth for the public schema as it
-- exists on the remote Supabase project. Generated from `supabase db dump`
-- on 2026-05-02; dead UPDATE policy on gacha_draws stripped (the table is
-- append-only and the frontend never PATCHes a draw row).
--
-- All future schema changes go in their own migration via:
--   npx supabase migration new <name>
-- Do not edit this file by hand.


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


-- Note on `pg_net`: Supabase pre-installs it in the `extensions` schema for
-- Edge Functions / webhook helpers. We deliberately do NOT declare it in this
-- baseline because `--schema=public` dumps don't include extensions schemas,
-- and the CLI's shadow Postgres often can't load pg_net itself, so any
-- declaration here causes more drift than it removes. As a result, every
-- `supabase db pull` will emit a phantom `drop extension "pg_net"` patch
-- file — discard it (do NOT push). Treat this as a known CLI quirk.


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."character_profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "inv_h" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "inv_s" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "is_default" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."character_profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."gacha_banners" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "hero_pool" "text"[] DEFAULT ARRAY[]::"text"[] NOT NULL,
    "rare_heroes" "text"[] DEFAULT ARRAY[]::"text"[] NOT NULL
);


ALTER TABLE "public"."gacha_banners" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."gacha_draws" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "banner_id" "uuid" NOT NULL,
    "hero_jp" "text" NOT NULL,
    "rarity" smallint DEFAULT 3 NOT NULL,
    "note" "text",
    "drawn_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."gacha_draws" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."gacha_draws_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."gacha_draws_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."gacha_draws_id_seq" OWNED BY "public"."gacha_draws"."id";



CREATE TABLE IF NOT EXISTS "public"."shares" (
    "slug" "text" NOT NULL,
    "blob" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "display_name" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "pinned" boolean DEFAULT false NOT NULL,
    CONSTRAINT "blob_size_limit" CHECK (("octet_length"(("blob")::"text") < 100000))
);


ALTER TABLE "public"."shares" OWNER TO "postgres";


ALTER TABLE ONLY "public"."gacha_draws" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."gacha_draws_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."character_profiles"
    ADD CONSTRAINT "character_profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."gacha_banners"
    ADD CONSTRAINT "gacha_banners_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."gacha_draws"
    ADD CONSTRAINT "gacha_draws_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."shares"
    ADD CONSTRAINT "shares_pkey" PRIMARY KEY ("slug");



CREATE INDEX "character_profiles_user_id_idx" ON "public"."character_profiles" USING "btree" ("user_id");



CREATE INDEX "gacha_banners_user_idx" ON "public"."gacha_banners" USING "btree" ("user_id", "is_active", "sort_order");



CREATE INDEX "gacha_draws_user_banner_drawn_idx" ON "public"."gacha_draws" USING "btree" ("user_id", "banner_id", "drawn_at" DESC);



CREATE INDEX "shares_created_at_idx" ON "public"."shares" USING "btree" ("created_at");



CREATE INDEX "shares_user_id_idx" ON "public"."shares" USING "btree" ("user_id") WHERE ("user_id" IS NOT NULL);



ALTER TABLE ONLY "public"."character_profiles"
    ADD CONSTRAINT "character_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."gacha_banners"
    ADD CONSTRAINT "gacha_banners_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."gacha_draws"
    ADD CONSTRAINT "gacha_draws_banner_id_fkey" FOREIGN KEY ("banner_id") REFERENCES "public"."gacha_banners"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."gacha_draws"
    ADD CONSTRAINT "gacha_draws_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shares"
    ADD CONSTRAINT "shares_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE "public"."character_profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."gacha_banners" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "gacha_banners_owner_delete" ON "public"."gacha_banners" FOR DELETE USING (("user_id" = "auth"."uid"()));



CREATE POLICY "gacha_banners_owner_insert" ON "public"."gacha_banners" FOR INSERT WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "gacha_banners_owner_select" ON "public"."gacha_banners" FOR SELECT USING (("user_id" = "auth"."uid"()));



CREATE POLICY "gacha_banners_owner_update" ON "public"."gacha_banners" FOR UPDATE USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



ALTER TABLE "public"."gacha_draws" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "gacha_draws_owner_delete" ON "public"."gacha_draws" FOR DELETE USING (("user_id" = "auth"."uid"()));



CREATE POLICY "gacha_draws_owner_insert" ON "public"."gacha_draws" FOR INSERT WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "gacha_draws_owner_select" ON "public"."gacha_draws" FOR SELECT USING (("user_id" = "auth"."uid"()));



CREATE POLICY "profiles_owner_delete" ON "public"."character_profiles" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "profiles_owner_insert" ON "public"."character_profiles" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "profiles_owner_select" ON "public"."character_profiles" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "profiles_owner_update" ON "public"."character_profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."shares" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "shares_anon_insert" ON "public"."shares" FOR INSERT TO "anon" WITH CHECK (("user_id" IS NULL));



CREATE POLICY "shares_auth_insert" ON "public"."shares" FOR INSERT TO "authenticated" WITH CHECK ((("user_id" = "auth"."uid"()) OR ("user_id" IS NULL)));



CREATE POLICY "shares_owner_delete" ON "public"."shares" FOR DELETE TO "authenticated" USING (("user_id" = "auth"."uid"()));



CREATE POLICY "shares_owner_update" ON "public"."shares" FOR UPDATE TO "authenticated" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "shares_public_select" ON "public"."shares" FOR SELECT USING (true);



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."character_profiles" TO "anon";
GRANT ALL ON TABLE "public"."character_profiles" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."character_profiles" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."gacha_banners" TO "anon";
GRANT ALL ON TABLE "public"."gacha_banners" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."gacha_banners" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."gacha_draws" TO "anon";
GRANT ALL ON TABLE "public"."gacha_draws" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."gacha_draws" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."gacha_draws_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."gacha_draws_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."gacha_draws_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."shares" TO "anon";
GRANT ALL ON TABLE "public"."shares" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."shares" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";
